version: "3"
services:
  db:
    container_name: pr1
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./server:/docker-entrypoint-initdb.d
      - db_volume:/var/lib/mysql
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
  server:
    container_name: pr1_server
    build: ./server
    volumes:
      - ./server:/var/www/html
    ports:
      - "8080:80"
volumes:
  db_volume: